import { TransactionHistory } from "./interface";

export const dummyTransactions: TransactionHistory[] = [
  {
    date: "March 29",
    time: "21:15",
    pay: { amount: 0.0012, currency: "ETH" },
    receive: { amount: 380, currency: "CRM" },
    batch: { stage: 26, phase: 172 },
    status: "Success",
  },
  {
    date: "March 29",
    time: "10:30",
    pay: { amount: 15, currency: "SOL" },
    receive: { amount: 9200, currency: "CRM" },
    batch: { stage: 26, phase: 172 },
    status: "Success",
  },
  {
    date: "March 28",
    time: "19:05",
    pay: { amount: 1.25, currency: "BNB" },
    receive: { amount: 6800, currency: "CRM" },
    batch: { stage: 26, phase: 172 },
    status: "Success",
  },
  {
    date: "March 26",
    time: "11:25",
    pay: { amount: 500, currency: "ADA" },
    receive: { amount: 500, currency: "ADA" },
    batch: { stage: 26, phase: 172 },
    status: "Pending",
  },
  {
    date: "March 25",
    time: "20:15",
    pay: { amount: 100, currency: "USDT" },
    receive: { amount: 10.465, currency: "CRM" },
    batch: { stage: 26, phase: 172 },
    status: "Success",
  },
  {
    date: "March 25",
    time: "19:48",
    pay: { amount: 7.74, currency: "BDAG" },
    receive: { amount: 8.465, currency: "CRM" },
    batch: { stage: 26, phase: 172 },
    status: "Failed",
  },
  {
    date: "March 24",
    time: "16:20",
    pay: { amount: 50, currency: "DOT" },
    receive: { amount: 600, currency: "CRM" },
    batch: { stage: 25, phase: 171 },
    status: "Success",
  },
  {
    date: "March 23",
    time: "14:05",
    pay: { amount: 200, currency: "XRP" },
    receive: { amount: 1800, currency: "CRM" },
    batch: { stage: 25, phase: 171 },
    status: "Success",
  },
  {
    date: "March 22",
    time: "09:55",
    pay: { amount: 2.5, currency: "AVAX" },
    receive: { amount: 350, currency: "CRM" },
    batch: { stage: 25, phase: 170 },
    status: "Pending",
  },
  {
    date: "March 21",
    time: "18:40",
    pay: { amount: 75, currency: "MATIC" },
    receive: { amount: 950, currency: "CRM" },
    batch: { stage: 25, phase: 170 },
    status: "Success",
  },
];
